#!/usr/bin/env python3
# -*- coding: utf8 -*-

import msgpack
import sys

try:
    if len(sys.argv) != 3:
        raise ValueError('Invalid number of arguments')

    arg1 = sys.argv[1]
    arg2 = sys.argv[2]

    data1 = msgpack.load(open(arg1, 'rb'))
    data2 = msgpack.load(open(arg2, 'rb'))

    if data1 != data2:
        raise ValueError('"{0}" != "{1}"'.format(arg1, arg2))

except (ValueError, TypeError) as e:
    print('\033[91m' + str(e) + '\nFAILED\n\033[0m')
    exit(1)

print('\033[92mSUCCEED\n\033[0m')
