#!/usr/bin/env python3
# -*- coding: utf8 -*-

import msgpackrpc

class EchoServer(object):
    def echo(self, *args):
        return args

server = msgpackrpc.Server(EchoServer())
server.listen(msgpackrpc.Address("localhost", 8000))
server.start()
